---
interfaces_map:
  - name: "Ethernet0/1"
    description: "Connected to CGM_CORE_02 interface Ethernet0/1"
    ip: "10.101.0.34"
    mask: "255.255.255.252"

# Configure VLANs on Distribution switch CGM_DIST_02
vlans_list:
  - id: 10
    name: "CGM_FINANCE"
  - id: 20
    name: "CGM_IT"
  - id: 30
    name: "CGM_OPERATIONS"

# Configure L2 EtherChannel to distribution switch CGM_DIST_01
l2_port_channels:
  - id: 10
    description: "L2 EtherChannel to Distribution Switch CGM_DIST_01"
    allowed_vlans: "10,20,30"
    members:
      - "Ethernet0/3"
      - "Ethernet1/0"
# Configure SVIs and HSRP on Distribution Switch CGM_DIST_02
svi_hsrp_list:
  - vlan_id: 10
    description: "GATEWAY FOR CGM_FINANCE"
    physical_ip: "10.101.10.3"
    mask: "255.255.255.0"
    hsrp_group: 10
    virtual_ip: "10.101.10.1"
    hsrp_priority: 100
  - vlan_id: 20
    description: "GATEWAY FOR CGM_IT"
    physical_ip: "10.101.20.3"
    mask: "255.255.255.0"
    hsrp_group: 20
    virtual_ip: "10.101.20.1"
    hsrp_priority: 100
  - vlan_id: 30
    description: "GATEWAY FOR CGM_OPERATIONS"
    physical_ip: "10.101.30.3"
    mask: "255.255.255.0"
    hsrp_group: 30
    virtual_ip: "10.101.30.1"
    hsrp_priority: 100
...